# These are supported funding model platforms

github: kalebpace
open_collective: # Replace with a single Open Collective username
liberapay: # Replace with a single Liberapay username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
