name: Build and Publish Pre-release
on:
  push:
    tags:
      # If tagged and is an odd semver, create Pre-release package
      # https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
      - 'v0.[13579]+.[0-9]+'
      - 'v[13579]+.[0-9]+.[0-9]+'

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}
  OVSX_PAT: ${{ secrets.OVSX_PAT }}

jobs:
  build-prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install Dependencies and Build VSIX Package
      id: build
      run: |
        TAG=${{ github.ref_name }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV

        npm install
        npx vsce package ${TAG#v} --no-git-tag-version --no-dependencies --pre-release

    - name: Create Pre-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        draft: false
        files: |
          ./balena-vscode-*.vsix
        
    - name: Publish to VSCode Marketplace & Open VSX Registry
      run: |
        npx vsce publish --packagePath ./balena-vscode-*.vsix
        npx ovsx publish --packagePath ./balena-vscode-*.vsix
