name: Build and Publish a Release
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}
  OVSX_PAT: ${{ secrets.OVSX_PAT }}
  VSIX_FILE_NAME: "*.vsix"

jobs:
  build-release-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies and Build
      run: |
        npm install
        npx vsce package patch --no-dependencies --pre-release

    - name: Create Release from Artifacts
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: 'Release'
        prerelease: false
        files: |
          ./$VSIX_FILE_NAME

    - name: Publish to VSCode Marketplace & Open VSX Registry
      run: |
        npx vsce publish --packagePath ./$VSIX_FILE_NAME
        npx ovsx publish --packagePath ./$VSIX_FILE_NAME