name: Build and Publish a Release
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}
  OVSX_PAT: ${{ secrets.OVSX_PAT }}
  VSIX_FILE_NAME: "*.vsix"

jobs:
  build-release-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Nix Flake Build
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build

    - name: Create Release from Artifacts
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: 'latest'
        prerelease: true
        files: |
          ./result/*

    - name: Publish to VSCode Marketplace & Open VSX Registry
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npx vsce publish --packagePath ./result/$VSIX_FILE_NAME
    - run: npx ovsx publish --packagePath ./result/$VSIX_FILE_NAME